import { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Importar Poppins de Google Fonts
const poppins = Poppins({
  subsets: ["latin"], // Ajusta según los caracteres que necesites
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Selecciona los pesos que vayas a utilizar
  variable: "--font-poppins", // Define la variable CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
